version: '3.8' # Or a recent stable version

services:
  neo4j:
    image: neo4j:4.4 # MVP plan specified 4.4, can use 5.x if preferred but ensure py2neo compatibility
    container_name: mvp_neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - mvp_neo4j_data:/data # Persist data
      # - ./neo4j/plugins:/plugins # If custom plugins are needed later
    environment:
      - NEO4J_AUTH=neo4j/testpassword # Change 'testpassword' to something more secure if desired, even for local
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G # As per MVP plan
      # NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # Required for Enterprise Edition, not strictly for Community
volumes:
  mvp_neo4j_data: 