[tool.black]
line-length = 88
target-version = ['py39'] # Adjust to your Python version
# include = '\\.pyi?$'
# exclude = '''
# /(
#     \\.git
#   | \\.hg
#   | \\.mypy_cache
#   | \\.tox
#   | \\.venv
#   | _build
#   | buck-out
#   | build
#   | dist
# )/
# '''

[tool.flake8]
# Or in setup.cfg as [flake8]
ignore = ['E203', 'E266', 'E501', 'W503'] # E501 is line length, black handles it. W503 is line break before binary operator.
max-line-length = 88 # Should match black
max-complexity = 10
exclude = [
    ".git",
    "__pycache__",
    "docs/source/conf.py",
    "old",
    "build",
    "dist",
    ".venv",
    "venv"
] 